# Site settings
title: Learning to Code
header-img: img/home-bg.png
email: art.rodriguez@live.com
copyright_name: fastmode
description: > # this means to ignore newlines until "baseurl:"
  My adventure into the world of ones and zeros
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: fastmode
github_username:  fastmode
learn_profile: fastmode
email_username: art.rodriguez@live.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
