# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Always Be Learning
email: fastmode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts and documentation of the dev space
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
twitter_username: fastmode
github_username:  fastmode
learn_profile: fastmode
email_username: fastmode@gmail.com

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
